[DISPLAY]
;InitialWindowPositionX/Y => -1 for centering
;FPSLimit => Limit the game's fps. Minimum of 30fps. Anything below will disable the fps limit.
;NVReflex. 0 : Disable, 1 : ReflexOn, 2 - ReflexWithBoost
;NVReflexIndicator => Enables the in-game latency metrics indication.
;Console => Enables the in-game console which is mapped to `/~. Will only work if the key is not already mapped.
GPUInfo=-622782538
GPUAdapter=0
InitialWindowPositionX=-1
InitialWindowPositionY=-1
Brightness=65.000000
FPSLimit=0
NVReflex=0
NVReflexIndicator=0
Console=0
FSRMode=0

[HARDWARE_INFO]
GPUVendor=NVIDIA
GPUDeviceId=0x1c03
GPUSubSysId=0x86191043
GPUDedicatedMemoryMB=6043
GPUScore=8642.000000
GPUScoreConf=0.841379
SystemMemoryMB=16314
CPUScore=3570.118652
HardwareNotificationEnable=1

[DISPLAY_SETTINGS]
;ResolutionXXX    => 0 for autodetection
;RefreshRate      => 0 will let DirectX pick it
;WindowMode       => 0 fullscreen / 1 windowed / 2 borderless
;AspectRatio      => 0 display / 1 resolution / 2..N as options
;VSync            => 0 disabled / 1 frame / 2 frames
;UseLetterbox     => 0 disabled / 1 enabled
;DefaultFOV       => Default vertical field of view (degrees)
;UseAmdAGS => Enables usage of AMD AGS library for additional info in crash reports
;VulkanWhitelistedLayers => Semicolon separated list, with all the Vulkan layers you want to enable, like VK_LAYER_VALVE_steam_fossilize;VK_LAYER_RTSS
Monitor=1
ResolutionWidth=1920
ResolutionHeight=1080
RefreshRate=165.000000
WindowMode=0
AspectRatio=0
VSync=0
MaxGPUBufferedFrame=1
UseLetterbox=0
DefaultFOV=90.000000
EnableAMDMultiDraw=1
UseAmdAGS=1
VulkanWhitelistedLayers=VK_LAYER_OW_OBS_HOOK;VK_LAYER_OW_OVERLAY

[QUALITY]
OverallQualityLevelName=Custom

[CUSTOM_QUALITY]
AntiAliasing=1
Geometry=3
Lighting=0
Shadow=1
Sharpness=10
Texture=1
VFX=1
TextureFiltering=2
Reflection=0
AO=0
LensEffects=0
DOF=0
AdaptiveRenderScalingTargetFPS=0
RenderScalingFactor=5
DLSSPerfQual=0

[READ_ONLY]
EngineSettingsVersion=1
DefaultValuesVersion=11

[INPUT]
RawInputMouseKeyboard=1
InvertAxisY=0
InvertMouseAxisY=0
Rumble=1
AimAssist=1
YawSensitivity=20
PitchSensitivity=10
DeadzoneLeftStick=15
DeadzoneRightStick=15
MouseSensitivity=22
MouseYawSensitivity=8
MousePitchSensitivity=8
MouseSensitivityMultiplierUnit=0.020000
MouseScroll=1
XFactorAiming=0.020000
ToggleAim=0
ToggleAimGamepad=0
ToggleLean=1
ToggleSprint=1
ToggleCrouch=1
ToggleProne=1
ToggleWalk=0
ToggleGadgetDeploymentGamepad=1
ToggleGadgetDeploymentKeyboard=1
AimDownSights=50
ADSGamepadUseSpecific=1
ADSGamepadSensitivityGlobal=50
ADSGamepadSensitivity1x=34
ADSGamepadSensitivity1xHalf=53
ADSGamepadSensitivity2x=54
ADSGamepadSensitivity2xHalf=54
ADSGamepadSensitivity3x=55
ADSGamepadSensitivity4x=55
ADSGamepadSensitivity5x=55
ADSGamepadSensitivity12x=84
ADSGamepadMultiplierUnit=0.020000
AdvancedGamepadOptions=0
GamepadHorizontalFullTiltBoostModifier=20
GamepadVerticalFullTiltBoostModifier=10
FullTiltBoostRampupDelay=0.000000
GamepadFullTiltBoostRampupTime=0.350000
ADSGamepadHorizontalFullTiltBoostModifier=30
ADSGamepadVerticalFullTiltBoostModifier=15
ADSFullTiltBoostRampupDelay=0.250000
ADSGamepadFullTiltBoostRampupTime=1.000000
OuterDeadzoneRightStick=0
GamepadLookDampeningTime=0.000000
AimDownSightsMouse=50
ADSMouseUseSpecific=1
ADSMouseSensitivityGlobal=50
ADSMouseSensitivity1x=40
ADSMouseSensitivity1xHalf=50
ADSMouseSensitivity2x=55
ADSMouseSensitivity2xHalf=65
ADSMouseSensitivity3x=72
ADSMouseSensitivity4x=74
ADSMouseSensitivity5x=74
ADSMouseSensitivity12x=99
ADSMouseMultiplierUnit=0.020000
ControlSchemeIndex=0
ControllerInputDevice=1

[AUDIO]
;Dynamic Range mode: (0) Hi-Fi, (1) TV, (2) Night Mode
;VoiceChatCaptureMode => 0 Auto / 1 Manual / 2 Push to talk
Subtitle=0
Volume=0.350000
VolumeMusic=0.000000
VolumeSoundEffects=1.000000
VolumeVoice=1.000000
DynamicRangeMode=0
VoiceChatPlaybackLevel=70
VoiceChatCaptureThresholdV2=35
VoiceChatCaptureMode=0
VoiceChatCaptureLevel=100
Mute=0
VoiceChatMuteAll=0
VoiceChatTeamOnly=1

[GAMEPLAY]
GameplayPingEnable=1

[ACCESSIBILITY]
TeamColorAllyIndex=0
TeamColorEnemyIndex=2
ColorBlindMode=0

[ONLINE]
;DataCenterHint => 
;    default (ping based)
;    playfab/australiaeast
;    playfab/brazilsouth
;    playfab/centralus
;    playfab/eastasia
;    playfab/eastus
;    playfab/japaneast
;    playfab/northeurope
;    playfab/southafricanorth
;    playfab/southcentralus
;    playfab/southeastasia
;    playfab/uaenorth
;    playfab/westeurope
;    playfab/westus

;
;if UseProxyAutoDiscovery is set to true, http_proxy or https_proxy or all_proxy and no_proxy are going to be looked up and used for all http calls
DataCenterHint=default
UseProxyAutoDiscovery=0

